export const SettingsErrorCode = {
  PROFILE_UPDATE_FAIL:   'SETTINGS_PROFILE_UPDATE_FAIL',
  PASSWORD_CHANGE_FAIL:  'SETTINGS_PASSWORD_CHANGE_FAIL',
  UNLINK_FAIL:           'SETTINGS_UNLINK_FAIL',
  WITHDRAW_FAIL:         'SETTINGS_WITHDRAW_FAIL',
  OTP_REQUEST_FAIL:      'SETTINGS_OTP_REQUEST_FAIL',
  OTP_VERIFY_FAIL:       'SETTINGS_OTP_VERIFY_FAIL',
} as const;
