export const MEMBER_ERRORS = {
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  MEMBER_ALREADY_EXISTS: 'MEMBER_ALREADY_EXISTS',
  MEMBER_FORBIDDEN: 'MEMBER_FORBIDDEN',
} as const;
export const MemberErrorCode = { AFFILIATE_CONNECT_FAIL: 'AFFILIATE_CONNECT_FAIL', CLUB_JOIN_FAIL: 'CLUB_JOIN_FAIL', SUBSCRIPTION_FAIL: 'SUBSCRIPTION_FAIL' } as const;
